# Generated by Django 3.1.7 on 2021-03-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210307_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='like',
        ),
    ]
