# Generated by Django 3.1.7 on 2021-03-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_places_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
